/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.atividade005;

import java.util.ArrayList;
import java.util.Random;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;

/**
 *
 * @author yurim
 */
public class Criacaoconta extends javax.swing.JDialog {

    /**
     * Creates new form Criacaoconta
     */
    public Criacaoconta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("Banco São Luís - Criação de Conta");
        jButtongerar.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonLimpar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButtonVoltar = new javax.swing.JButton();
        jTextID = new javax.swing.JTextField();
        jButtongerar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextNome = new javax.swing.JTextField();
        jTextCurso = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextSenha = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboTipoConta = new javax.swing.JComboBox<>();
        jButtonCriar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel1.setText("BANCO SÃO LUÍS");

        jButtonLimpar.setText("Limpar");

        jLabel2.setText("O numero da sua conta será:");

        jButtonVoltar.setText("Voltar ao inicio");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        jTextID.setEditable(false);

        jButtongerar.setText("Clique para gerar");
        jButtongerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtongerarActionPerformed(evt);
            }
        });

        jLabel3.setText("Digite aqui seu nome:");

        jLabel6.setText("Digite o nome do curso:");

        jTextNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextNomeKeyTyped(evt);
            }
        });

        jLabel4.setText("Digite aqui sua senha:");

        jTextSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextSenhaKeyTyped(evt);
            }
        });

        jLabel5.setText("Selecione abaixo o tipo de conta:");

        jComboTipoConta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Conta Especial", "Conta Poupança", "Conta Universitária", " " }));

        jButtonCriar.setText("Criar");
        jButtonCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCriarActionPerformed(evt);
            }
        });

        jLabel7.setText("*Apenas numeros");

        jLabel8.setText("*Apenas se selecionar conta universitária");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(130, 130, 130))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextNome)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonVoltar))
                    .addComponent(jTextCurso)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboTipoConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonCriar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonLimpar)))
                        .addGap(0, 220, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextID, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtongerar))
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jTextSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(0, 101, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtongerar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboTipoConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCriar)
                    .addComponent(jButtonLimpar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonVoltar)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed
    
    private void jButtongerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtongerarActionPerformed
        // TODO add your handling code here:
        Random random = new Random();
        int num = random.nextInt(1000);
        jTextID.setText(String.valueOf(num));
    }//GEN-LAST:event_jButtongerarActionPerformed
    
    ArrayList<Cliente> cliente = new ArrayList<>();
    ArrayList<Contaespecial> clienteE = new ArrayList<>();
    ArrayList<Contapoupanca> clienteP = new ArrayList<>();
    ArrayList<Contauniversitario> clienteU = new ArrayList<>();

    public void setClienteE(ArrayList<Contaespecial> clienteE) {
        this.clienteE = clienteE;
    }

    public void setClienteP(ArrayList<Contapoupanca> clienteP) {
        this.clienteP = clienteP;
    }

    public void setClienteU(ArrayList<Contauniversitario> clienteU) {
        this.clienteU = clienteU;
    }
    
    Inicio inicio;
    private void jButtonCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCriarActionPerformed
        // TODO add your handling code here:
        if(jTextID.getText().trim().isEmpty() || jTextNome.getText().trim().isEmpty() || jTextSenha.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos antes de prosseguir!", "Erro!", ERROR_MESSAGE);
        }else{
            String B = (String) jComboTipoConta.getSelectedItem();
            if(B == "Conta Especial"){
                Contaespecial c = new Contaespecial(jTextNome.getText(),Integer.parseInt(jTextID.getText()),jTextSenha.getText(), 0, 1);
                clienteE.add(c);
                JOptionPane.showMessageDialog(null, "Conta criada com sucesso! Abaixo segue as informações:\n"
                                + "Nome: "+c.getNome()+"\nNumero da Conta: "+c.getID()+"\nTipo da conta: "+c.tipoconta()+"\nSenha: "+c.getSenha(), "Sucesso!", INFORMATION_MESSAGE);
                
                jTextID.setText("");
                jTextNome.setText("");
                jTextSenha.setText("");
                jTextCurso.setText("");
                
            }
            if(B == "Conta Universitária"){
                if(jTextCurso.getText().trim().isEmpty()){
                    JOptionPane.showMessageDialog(null, "Preencha todos os campos antes de prosseguir!", "Erro!", ERROR_MESSAGE);
                }else{
                Contauniversitario c = new Contauniversitario(jTextCurso.getText(), jTextNome.getText(),Integer.parseInt(jTextID.getText()),jTextSenha.getText(), 0, 2);
                clienteU.add(c);
                JOptionPane.showMessageDialog(null, "Conta criada com sucesso! Abaixo segue as informações:\n"
                                + "Nome: "+c.getNome()+"\nNumero da Conta: "+c.getID()+"\nTipo da conta: "+c.tipoconta()+"\nCurso: "+c.getCurso()+"\nSenha: "+c.getSenha(), "Sucesso!", INFORMATION_MESSAGE);
                
                jTextID.setText("");
                jTextNome.setText("");
                jTextSenha.setText("");
                jTextCurso.setText("");
                }
                
            }
            if(B == "Conta Poupança"){
                Contapoupanca c = new Contapoupanca(0,jTextNome.getText(),Integer.parseInt(jTextID.getText()),jTextSenha.getText(), 0, 3);
                clienteP.add(c);
                JOptionPane.showMessageDialog(null, "Conta criada com sucesso! Abaixo segue as informações:\n"
                                + "Nome: "+c.getNome()+"\nNumero da Conta: "+c.getID()+"\nTipo da conta: "+c.tipoconta()+"\nSenha: "+c.getSenha(), "Sucesso!", INFORMATION_MESSAGE);
                
                jTextID.setText("");
                jTextNome.setText("");
                jTextSenha.setText("");
                jTextCurso.setText("");
            }

        }
    }//GEN-LAST:event_jButtonCriarActionPerformed

    private void jTextSenhaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextSenhaKeyTyped
        // TODO add your handling code here:
        String caracteres="0987654321";
            if(!caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
           }
    }//GEN-LAST:event_jTextSenhaKeyTyped

    private void jTextNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextNomeKeyTyped
        // TODO add your handling code here:
        String caracteres="AaBbCcDdEeFfGgHhIiJjLlKkMmNnOoPpQqRrSsTtUuVvXxYyWwZz´^~-";
            if(!caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
           }
    }//GEN-LAST:event_jTextNomeKeyTyped

    public void setCliente(ArrayList<Cliente> cliente) {
        this.cliente = cliente;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Criacaoconta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Criacaoconta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Criacaoconta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Criacaoconta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Criacaoconta dialog = new Criacaoconta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCriar;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JButton jButtongerar;
    private javax.swing.JComboBox<String> jComboTipoConta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextCurso;
    private javax.swing.JTextField jTextID;
    private javax.swing.JTextField jTextNome;
    private javax.swing.JTextField jTextSenha;
    // End of variables declaration//GEN-END:variables
}
