/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.atividade005;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;

/**
 *
 * @author yurim
 */
public class Inicio extends javax.swing.JFrame {
    
    private final Criacaoconta criar;

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        this.criar = new Criacaoconta(this,true);
        this.setTitle("Banco São Luís");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextNumeroConta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextSenha = new javax.swing.JTextField();
        jButtonEntrar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jLabelClicavel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboTipo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel1.setText("BANCO SÃO LUÍS");

        jLabel2.setText("Digite o numero da sua conta");

        jTextNumeroConta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextNumeroContaKeyTyped(evt);
            }
        });

        jLabel3.setText("Digite sua senha");

        jTextSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextSenhaKeyTyped(evt);
            }
        });

        jButtonEntrar.setText("Entrar");
        jButtonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntrarActionPerformed(evt);
            }
        });

        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jLabelClicavel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelClicavel.setText("Não possui conta? Clique aqui e abra já!");
        jLabelClicavel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelClicavelMouseClicked(evt);
            }
        });

        jLabel4.setText("Tipo da conta:");

        jComboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Conta Poupança", "Conta Universitária", "Conta Especial" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonEntrar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonLimpar))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)))
                        .addGap(0, 131, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabelClicavel))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTextSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextNumeroConta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel4))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextNumeroConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLimpar)
                    .addComponent(jButtonEntrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelClicavel)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


   

   

    
    private void jLabelClicavelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelClicavelMouseClicked
        // TODO add your handling code here:
        criar.setVisible(true);

    }//GEN-LAST:event_jLabelClicavelMouseClicked

    private void jButtonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntrarActionPerformed
        // TODO add your handling code here:
        if(jTextNumeroConta.getText().trim().isEmpty() || jTextSenha.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Para entrar na conta é necessario preencher todos os campos!", "ERRO!", ERROR_MESSAGE);      
        }else{
           String A = (String) jComboTipo.getSelectedItem();
            
            switch(A){
            
                case "Conta Universitária": 
                    for(Cliente d : criar.clienteU){
                    System.out.println(d.getID() + d.getSenha());
                    if(Integer.parseInt(jTextNumeroConta.getText()) == d.getID()){
                        if(Integer.parseInt(jTextSenha.getText()) == Integer.parseInt(d.getSenha())){     
                                    Interfaceuniversitario inter = new Interfaceuniversitario();
                                    inter.ID = d.getID();
                                    inter.setInter(criar.clienteU);
                                    inter.setVisible(true);
                                    jTextNumeroConta.setText("");
                                    jTextSenha.setText("");
                                    criar.setClienteU(inter.inter); 
                                    break;
                            }
                    }else{
                        JOptionPane.showMessageDialog(null, "Numero da Conta/Senha/Tipo conta errados! Insira novamente!", "ERRO!", ERROR_MESSAGE);
                        }
                    }
                case "Conta Especial": 
                    for(Cliente d : criar.clienteE){
                    System.out.println(d.getID() + d.getSenha());
                    if(Integer.parseInt(jTextNumeroConta.getText()) == d.getID()){
                        if(Integer.parseInt(jTextSenha.getText()) == Integer.parseInt(d.getSenha())){     
                                    InterfaceEspecial interE = new InterfaceEspecial();
                                    interE.ID = d.getID();
                                    interE.setInter(criar.clienteE);
                                    interE.setVisible(true);
                                    jTextNumeroConta.setText("");
                                    jTextSenha.setText("");
                                    criar.setClienteE(interE.inter); 
                            }
                    }else{
                        JOptionPane.showMessageDialog(null, "Numero da Conta/Senha/Tipo conta errados! Insira novamente!", "ERRO!", ERROR_MESSAGE);
                        }
                    }
                    break;
                case "Conta Poupança": 
                    for(Cliente d : criar.clienteP){
                    System.out.println(d.getID() + d.getSenha());
                    if(Integer.parseInt(jTextNumeroConta.getText()) == d.getID()){
                        if(Integer.parseInt(jTextSenha.getText()) == Integer.parseInt(d.getSenha())){     
                                    Interfacepoupanca interp = new Interfacepoupanca();
                                    interp.ID = d.getID();
                                    interp.setInter(criar.clienteP);
                                    interp.setVisible(true);
                                    jTextNumeroConta.setText("");
                                    jTextSenha.setText("");
                                    criar.setClienteP(interp.inter);
                            }
                    }else{
                        JOptionPane.showMessageDialog(null, "Numero da Conta/Senha/Tipo conta errados! Insira novamente!", "ERRO!", ERROR_MESSAGE);
                        }
                    }
                    break;
                    default:
                        JOptionPane.showMessageDialog(null, "Selecione o tipo da sua conta!", "ERRO!", ERROR_MESSAGE);
                        break;
            }           
            
        }
    }//GEN-LAST:event_jButtonEntrarActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        // TODO add your handling code here:
        jTextNumeroConta.setText("");
        jTextSenha.setText("");
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jTextNumeroContaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextNumeroContaKeyTyped
        // TODO add your handling code here:
        String caracteres="0987654321";
            if(!caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
           }
        
    }//GEN-LAST:event_jTextNumeroContaKeyTyped

    private void jTextSenhaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextSenhaKeyTyped
        // TODO add your handling code here:
        String caracteres="0987654321";
            if(!caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
           }
        
    }//GEN-LAST:event_jTextSenhaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEntrar;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JComboBox<String> jComboTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelClicavel;
    private javax.swing.JTextField jTextNumeroConta;
    private javax.swing.JTextField jTextSenha;
    // End of variables declaration//GEN-END:variables

    
}
