/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.atividade005;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;

/**
 *
 * @author yurim
 */
public class InterfaceEspecial extends javax.swing.JFrame {

    /**
     * Creates new form Interface1
     */
    public InterfaceEspecial() {
        initComponents();
        this.setTitle("Banco São Luís - Internet Banking");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonConfirmar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonConfirmar2 = new javax.swing.JButton();
        jButtonExibir1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButtonVoltar = new javax.swing.JButton();
        jTextTipoConta = new javax.swing.JTextField();
        jButtonExibir = new javax.swing.JButton();
        jLabelNome = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelInfo = new javax.swing.JLabel();
        jTextCE = new javax.swing.JTextField();
        jButtonExibir2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextSaldo = new javax.swing.JTextField();
        jTextSacar = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextDepositar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboTipo1 = new javax.swing.JComboBox<>();
        jComboTipo2 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jButtonConfirmar.setText("Confirmar");
        jButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel1.setText("BANCO SÃO LUÍS");

        jButtonConfirmar2.setText("Confirmar");
        jButtonConfirmar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmar2ActionPerformed(evt);
            }
        });

        jButtonExibir1.setText("Exibir");
        jButtonExibir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExibir1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Tipo da conta");

        jButtonVoltar.setText("Voltar ao Menu");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        jTextTipoConta.setEditable(false);
        jTextTipoConta.setText("-");

        jButtonExibir.setText("Exibir");
        jButtonExibir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExibirActionPerformed(evt);
            }
        });

        jLabelNome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelNome.setText("BEM VINDO A SUA CONTA, ****!");
        jLabelNome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelNomeMouseClicked(evt);
            }
        });

        jLabel2.setText("Saldo Devedor:");

        jLabelInfo.setText("*Clique acima para mostrar seu nome, caso deseje!");

        jTextCE.setEditable(false);
        jTextCE.setText("-");
        jTextCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCEActionPerformed(evt);
            }
        });

        jButtonExibir2.setText("Exibir");
        jButtonExibir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExibir2ActionPerformed(evt);
            }
        });

        jButton1.setText("Exibir informações sobre a conta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Saldo disponivel:");

        jTextSaldo.setEditable(false);
        jTextSaldo.setText("-");

        jTextSacar.setText("0");
        jTextSacar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextSacarKeyTyped(evt);
            }
        });

        jLabel6.setText("Depositar");

        jTextDepositar.setText("0");
        jTextDepositar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextDepositarKeyTyped(evt);
            }
        });

        jLabel7.setText("Sacar");

        jComboTipo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Saldo", "Credito Especial" }));

        jComboTipo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Saldo", "Credito Especial" }));

        jLabel8.setText("Tipo");

        jLabel9.setText("Tipo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(232, 232, 232))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelInfo)
                            .addComponent(jLabelNome))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jTextSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonExibir1)
                                    .addGap(55, 55, 55)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jTextTipoConta, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButtonExibir2))))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonVoltar)))
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextCE, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonExibir))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextDepositar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jComboTipo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(6, 6, 6))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jTextSacar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addGap(128, 128, 128)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jComboTipo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonConfirmar)
                                    .addComponent(jButtonConfirmar2))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabelNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelInfo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonExibir1)
                            .addComponent(jTextSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextTipoConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonExibir2))))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextCE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExibir))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextSacar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonConfirmar)
                    .addComponent(jComboTipo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextDepositar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonConfirmar2)
                    .addComponent(jComboTipo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVoltar)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    ArrayList<Contaespecial> inter = new ArrayList<>();
    int ID;
    
    private void jButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarActionPerformed
        // TODO add your handling code here:
        String C = (String) jComboTipo1.getSelectedItem();
        
        switch(C){
            
            case "Saldo":
                for(Contaespecial d : inter){
            if(d.getID() == ID){
                if(jTextDepositar.getText().trim().isEmpty()){
                    JOptionPane.showMessageDialog(null, "Valor invalido!", "ERRO!", ERROR_MESSAGE);
                    jTextDepositar.setText("0");
                }else{
                    d.sacar(Double.parseDouble(jTextSacar.getText()));
                    jTextSaldo.setText("-");
                    jTextCE.setText("-");
                    jTextDepositar.setText("0");
                }
            }
            }
                break;
                
            case "Credito Especial":
                for(Contaespecial d : inter){
            if(d.getID() == ID){
                if(jTextDepositar.getText().trim().isEmpty()){
                    JOptionPane.showMessageDialog(null, "Valor invalido!", "ERRO!", ERROR_MESSAGE);
                    jTextDepositar.setText("0");
                }else{
                    d.sacar(Double.parseDouble(jTextSacar.getText()), 1);
                    jTextSaldo.setText("-");
                    jTextCE.setText("-");
                    jTextDepositar.setText("0");
                }
            }
        }
            break;
            
            default:
                JOptionPane.showMessageDialog(null, "Insira um tipo para o saque!", "ERRO!", ERROR_MESSAGE);
                break;
                
        }
    }//GEN-LAST:event_jButtonConfirmarActionPerformed

    private void jButtonConfirmar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmar2ActionPerformed
        // TODO add your handling code here:
        String C = (String) jComboTipo2.getSelectedItem();
        
        switch(C){
            
            case "Saldo":
                for(Contaespecial d : inter){
            if(d.getID() == ID){
                if(jTextDepositar.getText().trim().isEmpty()){
                    JOptionPane.showMessageDialog(null, "Valor invalido!", "ERRO!", ERROR_MESSAGE);
                    jTextDepositar.setText("0");
                }else{
                    d.depositar(Double.parseDouble(jTextDepositar.getText()));
                    jTextSaldo.setText("-");
                    jTextCE.setText("-");
                    jTextDepositar.setText("0");
                }
            }
            }
                break;
                
            case "Credito Especial":
                for(Contaespecial d : inter){
            if(d.getID() == ID){
                if(jTextDepositar.getText().trim().isEmpty()){
                    JOptionPane.showMessageDialog(null, "Valor invalido!", "ERRO!", ERROR_MESSAGE);
                    jTextDepositar.setText("0");
                }else{
                    d.depositar(Double.parseDouble(jTextDepositar.getText()), 1);
                    jTextSaldo.setText("-");
                    jTextCE.setText("-");
                    jTextDepositar.setText("0");
                }
            }
        }
            break;
            
            default:
                JOptionPane.showMessageDialog(null, "Insira um tipo para o deposito!", "ERRO!", ERROR_MESSAGE);
                break;
                
        }
    }//GEN-LAST:event_jButtonConfirmar2ActionPerformed

    private void jButtonExibir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExibir1ActionPerformed
        // TODO add your handling code here:
        for(Contaespecial d : inter){
            if(d.getID() == ID){
                jTextSaldo.setText(String.valueOf(d.getSaldo()));
            }
        }
    }//GEN-LAST:event_jButtonExibir1ActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jLabelNomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNomeMouseClicked
        // TODO add your handling code here:
        for(Contaespecial d : inter){
            if(d.getID() == ID){
                jLabelNome.setText("BEM VINDO A SUA CONTA, "+d.getNome()+"!");
                jLabelInfo.setVisible(false);
            }
        }

    }//GEN-LAST:event_jLabelNomeMouseClicked

    public void setInter(ArrayList<Contaespecial> inter) {
        this.inter = inter;
    }

    private void jButtonExibir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExibir2ActionPerformed
        // TODO add your handling code here:
        for(Contaespecial d : inter){
            if(d.getID() == ID){
                jTextTipoConta.setText(d.tipoconta());
            }
        }

    }//GEN-LAST:event_jButtonExibir2ActionPerformed

    private void jTextCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCEActionPerformed

    private void jButtonExibirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExibirActionPerformed
        // TODO add your handling code here:
        for(Contaespecial d : inter){
            if(d.getID() == ID){
                jTextCE.setText(String.valueOf(d.getCreditoespecial()));
            }
        }
    }//GEN-LAST:event_jButtonExibirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         for(Contaespecial d : inter){
            if(d.getID() == ID){
                JOptionPane.showMessageDialog(null, "Abaixo segue as informações:\n"
                                + "Nome: "+d.getNome()+"\nNumero da Conta: "+d.getID()+"\nTipo da conta: "+d.tipoconta()+"\nSenha: "+d.getSenha(), "Informações da conta", INFORMATION_MESSAGE);
            }
        }            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextSacarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextSacarKeyTyped
        // TODO add your handling code here:
        String caracteres="0987654321.,";
            if(!caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
           }
    }//GEN-LAST:event_jTextSacarKeyTyped

    private void jTextDepositarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextDepositarKeyTyped
        // TODO add your handling code here:
        String caracteres="0987654321.,";
            if(!caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
           }
    }//GEN-LAST:event_jTextDepositarKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceEspecial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceEspecial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceEspecial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceEspecial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceEspecial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JButton jButtonConfirmar2;
    private javax.swing.JButton jButtonExibir;
    private javax.swing.JButton jButtonExibir1;
    private javax.swing.JButton jButtonExibir2;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JComboBox<String> jComboTipo1;
    private javax.swing.JComboBox<String> jComboTipo2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelInfo;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JTextField jTextCE;
    private javax.swing.JTextField jTextDepositar;
    private javax.swing.JTextField jTextSacar;
    private javax.swing.JTextField jTextSaldo;
    private javax.swing.JTextField jTextTipoConta;
    // End of variables declaration//GEN-END:variables
}
